const todoDatabase = [
  { id: 1, title: "Buy groceries", description: "Milk, eggs, bread, and vegetables" },
  { id: 2, title: "Morning workout", description: "30 minutes of cardio and 15 minutes strength training" },
  { id: 3, title: "Finish project report", description: "Complete the final draft for submission" },
  { id: 4, title: "Call plumber", description: "Fix the leaking kitchen sink" },
  { id: 5, title: "Read a chapter", description: "Read one chapter of 'Atomic Habits'" },
  { id: 6, title: "Clean garage", description: "Sort tools and organize storage" },
  { id: 7, title: "Reply to emails", description: "Respond to unread emails from yesterday" },
  { id: 8, title: "Team meeting", description: "Discuss Q3 goals with the team at 3 PM" },
  { id: 9, title: "Water plants", description: "Water the garden and indoor plants" },
  { id: 10, title: "Update resume", description: "Add new internship details and recent skills" },
  { id: 11, title: "Pay electricity bill", description: "Pay before the due date to avoid fine" },
  { id: 12, title: "Backup laptop", description: "Upload all important files to cloud" },
  { id: 13, title: "Doctor appointment", description: "Annual health checkup at 11 AM" },
  { id: 14, title: "Order books", description: "Purchase programming books online" },
  { id: 15, title: "Clean inbox", description: "Organize emails into folders" },
  { id: 16, title: "Review PRs", description: "Review pull requests on GitHub repo" },
  { id: 17, title: "Meditate", description: "10 minutes mindfulness meditation" },
  { id: 18, title: "Make dinner", description: "Cook pasta and salad" },
  { id: 19, title: "Research travel destinations", description: "Look up options for weekend getaway" },
  { id: 20, title: "Grocery delivery follow-up", description: "Check on delayed items from yesterday" },
  { id: 21, title: "Edit YouTube video", description: "Trim and add subtitles" },
  { id: 22, title: "Fix website bug", description: "Resolve issue with navbar overflow" },
  { id: 23, title: "Update LinkedIn", description: "Share new blog post and skills" },
  { id: 24, title: "Install Node.js", description: "Set up Node and npm on new system" },
  { id: 25, title: "Submit assignment", description: "Upload PDF to course portal" },
  { id: 26, title: "Practice DSA problems", description: "Solve 3 Leetcode medium problems" },
  { id: 27, title: "Attend webinar", description: "Join web development session at 5 PM" },
  { id: 28, title: "Organize bookshelf", description: "Sort books by genre and size" },
  { id: 29, title: "Fix bike chain", description: "Repair the bicycle before weekend ride" },
  { id: 30, title: "Plan weekend", description: "Make itinerary for hiking trip" },
];

module.exports = todoDatabase;
